package com.citrushack.besafegrandma

import kotlin.math.roundToInt

private const val MAX_MATCHES_IN_SUMMARY = 10

private data class ScamKeyword(val phrase: String, val weight: Int)

data class ScamHeuristicResult(
    val score: Int,
    val matchedPhrases: List<String>,
)

object ScamHeuristics {

    private val keywords = listOf(
        ScamKeyword("gift card", 12),
        ScamKeyword("wire transfer", 12),
        ScamKeyword("bank transfer", 10),
        ScamKeyword("bitcoin", 12),
        ScamKeyword("crypto", 10),
        ScamKeyword("cryptocurrency", 10),
        ScamKeyword("zelle", 10),
        ScamKeyword("venmo", 8),
        ScamKeyword("cash app", 8),
        ScamKeyword("western union", 12),
        ScamKeyword("moneygram", 10),
        ScamKeyword("prepaid", 8),
        ScamKeyword("reloadable", 6),
        ScamKeyword("google play card", 12),
        ScamKeyword("apple gift card", 12),
        ScamKeyword("steam card", 10),
        ScamKeyword("walmart gift card", 10),
        ScamKeyword("target gift card", 10),
        ScamKeyword("best buy gift card", 10),
        ScamKeyword("fee", 6),
        ScamKeyword("processing fee", 8),
        ScamKeyword("penalty", 8),
        ScamKeyword("fine", 6),
        ScamKeyword("late fee", 8),
        ScamKeyword("overdue", 8),
        ScamKeyword("past due", 8),
        ScamKeyword("warrant", 12),
        ScamKeyword("arrest", 12),
        ScamKeyword("police", 8),
        ScamKeyword("sheriff", 10),
        ScamKeyword("fbi", 12),
        ScamKeyword("irs", 12),
        ScamKeyword("social security", 12),
        ScamKeyword("ssn", 10),
        ScamKeyword("medicare", 10),
        ScamKeyword("visa", 6),
        ScamKeyword("mastercard", 6),
        ScamKeyword("credit card", 8),
        ScamKeyword("debit card", 8),
        ScamKeyword("routing number", 10),
        ScamKeyword("account number", 10),
        ScamKeyword("pin number", 12),
        ScamKeyword("one-time code", 12),
        ScamKeyword("otp", 10),
        ScamKeyword("verification code", 10),
        ScamKeyword("two factor", 8),
        ScamKeyword("2fa", 8),
        ScamKeyword("security code", 8),
        ScamKeyword("reset your password", 8),
        ScamKeyword("verify your account", 10),
        ScamKeyword("confirm your identity", 10),
        ScamKeyword("identity verification", 10),
        ScamKeyword("account suspended", 10),
        ScamKeyword("account locked", 10),
        ScamKeyword("compromised", 8),
        ScamKeyword("breach", 8),
        ScamKeyword("suspicious activity", 8),
        ScamKeyword("fraud department", 10),
        ScamKeyword("chargeback", 6),
        ScamKeyword("refund", 6),
        ScamKeyword("refund processing", 8),
        ScamKeyword("refund issued", 8),
        ScamKeyword("overpayment", 10),
        ScamKeyword("urgent", 6),
        ScamKeyword("immediately", 8),
        ScamKeyword("right now", 6),
        ScamKeyword("act now", 8),
        ScamKeyword("time sensitive", 8),
        ScamKeyword("do not hang up", 12),
        ScamKeyword("stay on the line", 10),
        ScamKeyword("keep this confidential", 12),
        ScamKeyword("don’t tell anyone", 12),
        ScamKeyword("do not tell", 10),
        ScamKeyword("secret", 8),
        ScamKeyword("confidential", 8),
        ScamKeyword("limited time", 6),
        ScamKeyword("guaranteed", 6),
        ScamKeyword("guarantee", 6),
        ScamKeyword("winner", 8),
        ScamKeyword("won", 8),
        ScamKeyword("lottery", 12),
        ScamKeyword("sweepstakes", 12),
        ScamKeyword("prize", 8),
        ScamKeyword("claim your prize", 10),
        ScamKeyword("grant", 8),
        ScamKeyword("federal grant", 10),
        ScamKeyword("government grant", 10),
        ScamKeyword("student loan", 6),
        ScamKeyword("loan forgiveness", 10),
        ScamKeyword("debt relief", 10),
        ScamKeyword("consolidation", 6),
        ScamKeyword("tech support", 10),
        ScamKeyword("microsoft", 8),
        ScamKeyword("apple support", 8),
        ScamKeyword("amazon", 6),
        ScamKeyword("paypal", 8),
        ScamKeyword("ebay", 6),
        ScamKeyword("your computer", 6),
        ScamKeyword("virus", 8),
        ScamKeyword("malware", 10),
        ScamKeyword("hacked", 10),
        ScamKeyword("remote access", 12),
        ScamKeyword("screen sharing", 10),
        ScamKeyword("download this", 8),
        ScamKeyword("install", 6),
        ScamKeyword("application", 4),
        ScamKeyword("secure your account", 8),
        ScamKeyword("update your information", 6),
        ScamKeyword("payment required", 8),
        ScamKeyword("pay now", 10),
        ScamKeyword("past due amount", 8),
        ScamKeyword("final notice", 10),
        ScamKeyword("last warning", 10),
        ScamKeyword("sue", 10),
        ScamKeyword("lawsuit", 10),
        ScamKeyword("legal action", 12),
        ScamKeyword("settlement", 8),
        ScamKeyword("bank", 6),
        ScamKeyword("billing", 6),
        ScamKeyword("statement", 4),
        ScamKeyword("insurance", 6),
        ScamKeyword("policy", 4),
        ScamKeyword("premium", 6),
        ScamKeyword("claim", 6),
        ScamKeyword("deliver", 4),
        ScamKeyword("package", 4),
        ScamKeyword("customs", 8),
        ScamKeyword("border", 6),
        ScamKeyword("immigration", 10),
        ScamKeyword("deportation", 12),
        ScamKeyword("suspension", 8),
        ScamKeyword("disconnected", 6),
        ScamKeyword("service will be terminated", 10),
        ScamKeyword("press 1", 6),
        ScamKeyword("press one", 6),
        ScamKeyword("robot", 4),
        ScamKeyword("call back", 6),
        ScamKeyword("verify", 6),
        ScamKeyword("banking", 6),
        ScamKeyword("routing", 6),
        ScamKeyword("transfer", 6),
        ScamKeyword("wire", 8),
        ScamKeyword("payment", 6),
        ScamKeyword("card", 4),
        ScamKeyword("access your computer", 10),
        ScamKeyword("refund department", 10),
        ScamKeyword("security department", 8),
        ScamKeyword("government", 8),
        ScamKeyword("official", 6),
        ScamKeyword("badge number", 10),
        ScamKeyword("case number", 8),
        ScamKeyword("reference number", 8),
        ScamKeyword("verification", 6),
        ScamKeyword("urgent response", 8),
        ScamKeyword("final attempt", 8),
        ScamKeyword("freeze your account", 10),
        ScamKeyword("suspend your account", 10),
        ScamKeyword("verify your social security", 12),
        ScamKeyword("social security administration", 12),
        ScamKeyword("press", 4),
        ScamKeyword("gift", 6),
        ScamKeyword("card number", 10),
        ScamKeyword("barcode", 6),
        ScamKeyword("scratch", 6),
        ScamKeyword("activation", 6),
        ScamKeyword("unlock", 8),
        ScamKeyword("bypass", 8),
        ScamKeyword("remote", 8),
        ScamKeyword("remote control", 10),
        ScamKeyword("desktop", 6),
        ScamKeyword("refund support", 8),
        ScamKeyword("transaction", 6),
        ScamKeyword("suspicious", 6),
        ScamKeyword("courier", 6),
        ScamKeyword("cashier", 6),
        ScamKeyword("bitcoin atm", 12),
        ScamKeyword("scan the qr", 10),
        ScamKeyword("qr code", 8),
        ScamKeyword("remove funds", 8),
        ScamKeyword("secure funds", 8),
        ScamKeyword("safe account", 10),
        ScamKeyword("government account", 10),
        ScamKeyword("hold funds", 8),
        ScamKeyword("protect your money", 8),
        ScamKeyword("under investigation", 10),
        ScamKeyword("verify your bank", 10),
        ScamKeyword("legal department", 8),
        ScamKeyword("fraudulent", 8),
        ScamKeyword("compensation", 6),
        ScamKeyword("overcharge", 6),
        ScamKeyword("reimburse", 6),
        ScamKeyword("install anydesk", 12),
        ScamKeyword("teamviewer", 10),
        ScamKeyword("anydesk", 10),
        ScamKeyword("quick assist", 10),
        ScamKeyword("chrome remote", 10),
        ScamKeyword("allow access", 10),
        ScamKeyword("refund you", 8),
        ScamKeyword("withdraw", 6),
        ScamKeyword("cash withdrawal", 8),
        ScamKeyword("atm", 6),
        ScamKeyword("bank employee", 8),
        ScamKeyword("branch", 6),
        ScamKeyword("courthouse", 10),
        ScamKeyword("jury duty", 10),
        ScamKeyword("missed jury", 10),
        ScamKeyword("jury summons", 10),
        ScamKeyword("consumer protection", 6),
        ScamKeyword("regulator", 6),
        ScamKeyword("federal", 6),
        ScamKeyword("customs and border", 10),
        ScamKeyword("package seized", 10),
        ScamKeyword("contraband", 10),
        ScamKeyword("illegal", 8),
        ScamKeyword("police report", 8),
        ScamKeyword("investigator", 8),
        ScamKeyword("investigation", 8),
        ScamKeyword("treasury", 10),
        ScamKeyword("marshal", 10),
        ScamKeyword("order", 4),
        ScamKeyword("subscription", 6),
        ScamKeyword("auto-renew", 6),
        ScamKeyword("renewal", 6),
        ScamKeyword("charge", 6),
        ScamKeyword("merchant", 4),
        ScamKeyword("billing error", 6),
        ScamKeyword("accounting", 4),
        ScamKeyword("banking app", 6),
        ScamKeyword("mobile deposit", 6),
        ScamKeyword("mobile check", 6),
        ScamKeyword("check", 4),
        ScamKeyword("check number", 6),
        ScamKeyword("gift code", 8),
        ScamKeyword("code", 4),
        ScamKeyword("voucher", 8),
        ScamKeyword("prepaid card", 10),
        ScamKeyword("load", 6),
        ScamKeyword("reload", 6),
        ScamKeyword("purchase", 6),
        ScamKeyword("store", 4),
        ScamKeyword("retailer", 4),
        ScamKeyword("barcode number", 8),
        ScamKeyword("scratch off", 6),
        ScamKeyword("pin", 8),
        ScamKeyword("login", 6),
        ScamKeyword("password", 6),
        ScamKeyword("username", 6),
        ScamKeyword("security", 4),
        ScamKeyword("approve the payment", 10),
        ScamKeyword("confirm the transfer", 10),
        ScamKeyword("keep the line open", 10),
        ScamKeyword("do not disconnect", 10),
        ScamKeyword("do not share", 10),
        ScamKeyword("share your screen", 10),
        ScamKeyword("bank details", 8),
        ScamKeyword("verification number", 8),
        ScamKeyword("security question", 8),
        ScamKeyword("ssn number", 10),
        ScamKeyword("social security number", 12),
        ScamKeyword("open a new account", 10),
        ScamKeyword("move your money", 10),
        ScamKeyword("transfer your funds", 12),
        ScamKeyword("protect your account", 8),
        ScamKeyword("secure account", 8),
        ScamKeyword("safe account", 10),
        ScamKeyword("trusted account", 8),
        ScamKeyword("federal reserve", 10),
        ScamKeyword("identity theft", 10),
        ScamKeyword("compromised account", 10),
        ScamKeyword("hacker", 10),
        ScamKeyword("refund scam", 10),
        ScamKeyword("investment", 6),
        ScamKeyword("guaranteed returns", 10),
        ScamKeyword("crypto investment", 10),
        ScamKeyword("forex", 8),
        ScamKeyword("stock", 6),
        ScamKeyword("profit", 6),
        ScamKeyword("double your money", 12),
        ScamKeyword("risk free", 10),
        ScamKeyword("romance", 6),
        ScamKeyword("online relationship", 8),
        ScamKeyword("emergency", 8),
        ScamKeyword("grandma", 6),
        ScamKeyword("grandpa", 6),
        ScamKeyword("bail", 12),
        ScamKeyword("bail bonds", 12),
        ScamKeyword("kidnapped", 12),
        ScamKeyword("hospital", 6),
        ScamKeyword("medical emergency", 10),
        ScamKeyword("donation", 6),
        ScamKeyword("charity", 6),
        ScamKeyword("orphan", 8),
        ScamKeyword("relief fund", 8),
        ScamKeyword("disaster", 6),
        ScamKeyword("gas card", 8),
        ScamKeyword("target", 4),
        ScamKeyword("best buy", 4),
        ScamKeyword("walmart", 4),
        ScamKeyword("apple", 4),
        ScamKeyword("google", 4),
        ScamKeyword("amazon support", 8),
        ScamKeyword("amazon charge", 8),
        ScamKeyword("paypal charge", 8),
        ScamKeyword("paypal support", 8),
        ScamKeyword("bank fraud", 10),
        ScamKeyword("fraud alert", 10),
        ScamKeyword("account takeover", 10),
        ScamKeyword("security alert", 8),
        ScamKeyword("verification required", 10),
        ScamKeyword("account verification", 10),
        ScamKeyword("transaction pending", 8),
        ScamKeyword("pending charge", 8),
        ScamKeyword("do not ignore", 8),
        ScamKeyword("immediate action", 10),
        ScamKeyword("urgent action", 10),
        ScamKeyword("press to speak", 6),
        ScamKeyword("connect you", 4),
        ScamKeyword("call center", 6),
        ScamKeyword("representative", 4),
        ScamKeyword("supervisor", 4),
        ScamKeyword("manager", 4),
        ScamKeyword("authorization", 6),
        ScamKeyword("authorize", 6),
        ScamKeyword("authorize payment", 10),
        ScamKeyword("unusual login", 8),
        ScamKeyword("suspicious login", 8),
        ScamKeyword("failed login", 6),
        ScamKeyword("account access", 8),
        ScamKeyword("password reset", 8),
        ScamKeyword("temporary password", 8),
        ScamKeyword("verification call", 8),
        ScamKeyword("banking alert", 8),
        ScamKeyword("secure transfer", 10),
        ScamKeyword("protect funds", 10),
        ScamKeyword("safe keeping", 8),
        ScamKeyword("court", 6),
        ScamKeyword("judge", 8),
        ScamKeyword("case", 6),
        ScamKeyword("tax", 8),
        ScamKeyword("taxes", 8),
        ScamKeyword("tax debt", 10),
        ScamKeyword("tax lien", 10),
        ScamKeyword("tax fraud", 10),
        ScamKeyword("irs agent", 12),
        ScamKeyword("federal agent", 12),
        ScamKeyword("badge", 8),
        ScamKeyword("department", 4),
        ScamKeyword("official notice", 8),
        ScamKeyword("notice", 4),
        ScamKeyword("urgent notice", 8),
        ScamKeyword("service interruption", 8),
        ScamKeyword("disconnection", 8),
        ScamKeyword("telecom", 6),
        ScamKeyword("utility", 6),
        ScamKeyword("power", 6),
        ScamKeyword("electric", 6),
        ScamKeyword("gas", 6),
        ScamKeyword("water", 6),
        ScamKeyword("utility bill", 8),
        ScamKeyword("past due bill", 8),
        ScamKeyword("final bill", 8),
    )

    fun analyze(transcript: String): ScamHeuristicResult {
        val normalized = normalize(transcript)
        if (normalized.isBlank()) {
            return ScamHeuristicResult(score = 0, matchedPhrases = emptyList())
        }

        val matches = mutableListOf<Pair<String, Int>>()
        keywords.forEach { keyword ->
            if (normalized.contains(" ${keyword.phrase} ")) {
                matches.add(keyword.phrase to keyword.weight)
            }
        }

        val uniqueMatches = matches
            .distinctBy { it.first }
            .sortedByDescending { it.second }

        val rawScore = uniqueMatches.sumOf { it.second }
        val matchCount = uniqueMatches.size
        val scaled = (rawScore * 0.9 + matchCount * 2.5).roundToInt()

        val score = scaled.coerceIn(0, 100)
        val phrases = uniqueMatches.map { it.first }.take(MAX_MATCHES_IN_SUMMARY)

        return ScamHeuristicResult(score = score, matchedPhrases = phrases)
    }

    private fun normalize(text: String): String {
        val cleaned = text.lowercase()
            .replace(Regex("[^a-z0-9]+"), " ")
            .trim()
        return " $cleaned "
    }
}
